let songs = [
  {
    name: 'Ordinary Song - Elli(Cover Ins)',
    artist: 'Marc Velasco',
    img: 'img1',
    audio: 'ordinary song',
  },
  {
    name: 'Maybe this time - Elli(Cover)',
    artist: 'Micheal Murphy',
    img: 'img6',
    audio: 'maybe',
  },
  {
    name: 'Celeste - Ins',
    artist: 'Tothapi',
    img: 'img2',
    audio: 'celeste',
  },
  {
    name: 'Sometimes - Elli(Cover Ins)',
    artist: 'Britney Spears',
    img: 'img3',
    audio: 'sometimes',
  },
  {
    name: 'Drunk - Elli(Cover)',
    artist: 'Keshi',
    img: 'img4',
    audio: 'drunk',
  },
  {
    name: 'Nothing - Elli(Cover)',
    artist: 'Bruno Major',
    img: 'img5',
    audio: 'nothing',
  },
  {
    name: 'When i met you - Elli(Cover)',
    artist: 'APO Hiking Society',
    img: 'img10',
    audio: 'when',
  },
  {
    name: 'Lifetime - Elli(Cover)',
    artist: 'Ben&Ben',
    img: 'img7',
    audio: 'lifetime',
  },
  {
    name: 'Starting over again - Elli(Cover)',
    artist: 'Natalie Cole',
    img: 'img8',
    audio: 'starting',
  },
  {
    name: "Babalik sa'yo - Elli(Cover)",
    artist: 'Moira Dela Torre',
    img: 'img9',
    audio: 'babalik',
  },
  {
    name: 'Paraluman - Elli(Cover)',
    artist: 'Adie',
    img: 'img16',
    audio: 'paraluman',
  },
  {
    name: 'Leaving on a jet plane - Elli(Cover)',
    artist: 'John Denver',
    img: 'img11',
    audio: 'jet',
  },
  {
    name: "You can't hurry love - Elli(Cover)",
    artist: 'Phil Collins',
    img: 'img12',
    audio: 'love',
  },
  {
    name: 'Leaves - Elli(Cover)',
    artist: 'Ben&Ben',
    img: 'img13',
    audio: 'leaves',
  },
  {
    name: 'Build me up buttercup - Elli(Cover)',
    artist: 'The Foundations',
    img: 'img14',
    audio: 'buttercup',
  },
  {
    name: 'I love you 3000 - Elli(Cover)',
    artist: 'Stephanie Poetri',
    img: 'img15',
    audio: '3000',
  },
];
